apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    app: postgresql
  name: vol002
spec:
  capacity:
    storage: 25Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/tmp/vol002"
