apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    app: redis
  name: vol003
spec:
  capacity:
    storage: 25Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/tmp/cvat-redis"
