apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    app: cvat-app
    tier: backend
  name: vol001
spec:
  capacity:
    storage: 25Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/tmp/cvat-backend-data"
